# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginMubu(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/")
                .get("https://mubu.com/")
                .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/app/edit/home/661QUvKgTwP",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "csrf_token": "69a1e53c-02f3-410d-98bf-9b43fafd6b2b",
                    "SESSION": "dcae292a-6685-4f4e-8721-5036a84dea9c",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616739745",
                    "_ga": "GA1.2.837004326.1616739746",
                    "_gid": "GA1.2.2101171127.1616739746",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_gat": "1",
                    "reg_prepareId": "1786d370db8-1786d370d14-4998-b096-2e076ed0a3b2",
                    "reg_focusId": "97e3bcb3-3428-4998-b096-1786d37106c",
                    "_gat_UA-77727571-3": "1",
                    "SLARDAR_WEB_ID": "8f7d63b9-e6ae-4ca3-921e-31e7d7f1ff5b",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616740068",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
                .get("https://mubu.com/login")
                .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "csrf_token": "69a1e53c-02f3-410d-98bf-9b43fafd6b2b",
                    "SESSION": "dcae292a-6685-4f4e-8721-5036a84dea9c",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616739745",
                    "_ga": "GA1.2.837004326.1616739746",
                    "_gid": "GA1.2.2101171127.1616739746",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_gat": "1",
                    "reg_prepareId": "1786d370db8-1786d370d14-4998-b096-2e076ed0a3b2",
                    "reg_focusId": "97e3bcb3-3428-4998-b096-1786d37106c",
                    "_gat_UA-77727571-3": "1",
                    "SLARDAR_WEB_ID": "80861bad-9f39-49ee-b4a3-ce6d9f2c7f54",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616740074",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
                .get("https://mubu.com/login/password")
                .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "csrf_token": "69a1e53c-02f3-410d-98bf-9b43fafd6b2b",
                    "SESSION": "dcae292a-6685-4f4e-8721-5036a84dea9c",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616739745",
                    "_ga": "GA1.2.837004326.1616739746",
                    "_gid": "GA1.2.2101171127.1616739746",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_gat_UA-77727571-3": "1",
                    "reg_prepareId": "1786d37c7b0-1786d37c7af-4d75-8fc8-554f2ec7533d",
                    "SLARDAR_WEB_ID": "06932062-c15f-4bad-8bcb-e357c941bed1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616740076",
                    "reg_focusId": "057d21ac-4d7b-4d75-8fc8-1786d37cb25",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
                .post("https://mubu.com/api/login/submit")
                .with_headers(
                **{
                    "content-length": "51",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "csrf_token": "69a1e53c-02f3-410d-98bf-9b43fafd6b2b",
                    "SESSION": "dcae292a-6685-4f4e-8721-5036a84dea9c",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616739745",
                    "_ga": "GA1.2.837004326.1616739746",
                    "_gid": "GA1.2.2101171127.1616739746",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_gat_UA-77727571-3": "1",
                    "reg_prepareId": "1786d37c7b0-1786d37c7af-4d75-8fc8-554f2ec7533d",
                    "reg_focusId": "057d21ac-4d7b-4d75-8fc8-1786d37cb25",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "49238371-d652-4fac-ad94-4d54b35fa7b8",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616740078",
                }
            )
                .with_data(
                {"phone": "17876253458", "password": "q992926186", "remember": "true"}
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
                .get("https://mubu.com/app")
                .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "csrf_token": "69a1e53c-02f3-410d-98bf-9b43fafd6b2b",
                    "SESSION": "dcae292a-6685-4f4e-8721-5036a84dea9c",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616739745",
                    "_ga": "GA1.2.837004326.1616739746",
                    "_gid": "GA1.2.2101171127.1616739746",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_gat_UA-77727571-3": "1",
                    "reg_prepareId": "1786d37c7b0-1786d37c7af-4d75-8fc8-554f2ec7533d",
                    "reg_focusId": "057d21ac-4d7b-4d75-8fc8-1786d37cb25",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "49238371-d652-4fac-ad94-4d54b35fa7b8",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616740078",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "user_persistence": "e12a1282-0f42-4a31-b9c3-c6ffe6b1b677",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
                .post("https://api2.mubu.com/v3/api/user/profile")
                .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "eed8f5a1-e227-4547-bffa-5cfcfba95bda",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_data("")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
                .get("https://api2.mubu.com/v3/api/list/star_relation/get")
                .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "e1e94cf0-6ca9-4deb-9c1a-12492e77cfdd",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
                .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
                .with_headers(
                **{
                    "content-length": "12",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "31663179-f271-4778-8fe9-0a915a72a20d",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"start": ""})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
                .post("https://api2.mubu.com/v3/api/message/get_message_unread")
                .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "62e1e189-7ab4-4045-b8e8-c4039926f501",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"page": 1})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
                .post("https://api2.mubu.com/v3/api/user/get_user_params")
                .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "f50b144a-af1f-4f99-a3ad-45d8365566dc",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_data("")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
                .post("https://api2.mubu.com/v3/api/advertisement/get")
                .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "fa632c1b-937e-4d5d-9c5a-25d243ccb698",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"type": 1})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
                .post("https://api2.mubu.com/v3/api/list/item_count")
                .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "1e04f55b-9ab9-440f-b6be-b20b9f927dce",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"folderId": 0, "source": "home"})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        )
    ]


if __name__ == "__main__":
    TestCaseMubu().test_start()
