# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubu(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/")
            .get("https://mubu.com/")
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/app/edit/home/661QUvKgTwP",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "csrf_token": "69a1e53c-02f3-410d-98bf-9b43fafd6b2b",
                    "SESSION": "dcae292a-6685-4f4e-8721-5036a84dea9c",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616739745",
                    "_ga": "GA1.2.837004326.1616739746",
                    "_gid": "GA1.2.2101171127.1616739746",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_gat": "1",
                    "reg_prepareId": "1786d370db8-1786d370d14-4998-b096-2e076ed0a3b2",
                    "reg_focusId": "97e3bcb3-3428-4998-b096-1786d37106c",
                    "_gat_UA-77727571-3": "1",
                    "SLARDAR_WEB_ID": "8f7d63b9-e6ae-4ca3-921e-31e7d7f1ff5b",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616740068",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
            .get("https://mubu.com/login")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "csrf_token": "69a1e53c-02f3-410d-98bf-9b43fafd6b2b",
                    "SESSION": "dcae292a-6685-4f4e-8721-5036a84dea9c",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616739745",
                    "_ga": "GA1.2.837004326.1616739746",
                    "_gid": "GA1.2.2101171127.1616739746",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_gat": "1",
                    "reg_prepareId": "1786d370db8-1786d370d14-4998-b096-2e076ed0a3b2",
                    "reg_focusId": "97e3bcb3-3428-4998-b096-1786d37106c",
                    "_gat_UA-77727571-3": "1",
                    "SLARDAR_WEB_ID": "80861bad-9f39-49ee-b4a3-ce6d9f2c7f54",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616740074",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("https://mubu.com/login/password")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "csrf_token": "69a1e53c-02f3-410d-98bf-9b43fafd6b2b",
                    "SESSION": "dcae292a-6685-4f4e-8721-5036a84dea9c",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616739745",
                    "_ga": "GA1.2.837004326.1616739746",
                    "_gid": "GA1.2.2101171127.1616739746",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_gat_UA-77727571-3": "1",
                    "reg_prepareId": "1786d37c7b0-1786d37c7af-4d75-8fc8-554f2ec7533d",
                    "SLARDAR_WEB_ID": "06932062-c15f-4bad-8bcb-e357c941bed1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616740076",
                    "reg_focusId": "057d21ac-4d7b-4d75-8fc8-1786d37cb25",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "content-length": "51",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "csrf_token": "69a1e53c-02f3-410d-98bf-9b43fafd6b2b",
                    "SESSION": "dcae292a-6685-4f4e-8721-5036a84dea9c",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616739745",
                    "_ga": "GA1.2.837004326.1616739746",
                    "_gid": "GA1.2.2101171127.1616739746",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_gat_UA-77727571-3": "1",
                    "reg_prepareId": "1786d37c7b0-1786d37c7af-4d75-8fc8-554f2ec7533d",
                    "reg_focusId": "057d21ac-4d7b-4d75-8fc8-1786d37cb25",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "49238371-d652-4fac-ad94-4d54b35fa7b8",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616740078",
                }
            )
            .with_data(
                {"phone": "17876253458", "password": "q992926186", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
            .get("https://mubu.com/app")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "csrf_token": "69a1e53c-02f3-410d-98bf-9b43fafd6b2b",
                    "SESSION": "dcae292a-6685-4f4e-8721-5036a84dea9c",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616739745",
                    "_ga": "GA1.2.837004326.1616739746",
                    "_gid": "GA1.2.2101171127.1616739746",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_gat_UA-77727571-3": "1",
                    "reg_prepareId": "1786d37c7b0-1786d37c7af-4d75-8fc8-554f2ec7533d",
                    "reg_focusId": "057d21ac-4d7b-4d75-8fc8-1786d37cb25",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "49238371-d652-4fac-ad94-4d54b35fa7b8",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616740078",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "user_persistence": "e12a1282-0f42-4a31-b9c3-c6ffe6b1b677",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "eed8f5a1-e227-4547-bffa-5cfcfba95bda",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "e1e94cf0-6ca9-4deb-9c1a-12492e77cfdd",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "content-length": "12",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "31663179-f271-4778-8fe9-0a915a72a20d",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "62e1e189-7ab4-4045-b8e8-c4039926f501",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "f50b144a-af1f-4f99-a3ad-45d8365566dc",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "fa632c1b-937e-4d5d-9c5a-25d243ccb698",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "1e04f55b-9ab9-440f-b6be-b20b9f927dce",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_folder")
            .post("https://api2.mubu.com/v3/api/list/create_folder")
            .with_headers(
                **{
                    "content-length": "49",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "e302eee1-a45f-4857-920e-2e04423d1fbf",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"name": "hogwarts_demo", "folderId": "79gUlbrtrgP"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "42",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "859f59fd-2abc-454c-b446-bf5ce0f67558",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "6RqNlAlNnMP", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "35",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "b1711b49-2b71-4650-b7dd-e189e68fd298",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "6RqNlAlNnMP", "type": 0})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "dab5d46f-d08a-4f1a-a943-f1abc0045648",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "content-length": "37",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "aac64b9f-8b71-4bf2-81fd-69868144a140",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "7a_5fk_ROMP", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "e6a3d676-1f87-41b0-96a0-18eca12928ff",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"document_id": "7a_5fk_ROMP"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "x-request-id": "306f52e4-c18a-452b-88ad-000adb471518",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "e32dbe0a-f343-4f01-9238-86397c85b9ce",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "7a_5fk_ROMP"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/node/count")
            .post("https://api2.mubu.com/v3/api/refer/node/count")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "ce3c823e-f5b9-44d8-945a-90539293f962",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "7a_5fk_ROMP"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.mubu.com/v3/api/colla/members")
            .with_params(
                **{"memberId": "8645129269811969", "documentId": "7a_5fk_ROMP"}
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.mubu.com/v3/api/colla/members")
            .with_params(
                **{"memberId": "8645129269811969", "documentId": "7a_5fk_ROMP"}
            )
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "request-id": "members:8645129269811969:1616740121286",
                    "x-request-id": "81bc5674-b738-4bc2-8157-032e1466cf7e",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "404",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8645129269811969",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "request-id": "MESSAGE:11519203:8645129269811969:3",
                    "x-request-id": "70517b78-199b-4cc2-a2d2-e3b903b1c730",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:11519203:8645129269811969:3",
                    "token": "7a_5fk_ROMP",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "7a_5fk_ROMP",
                            "version": 0,
                            "content": [
                                {"name": "nameChanged", "title": "d", "original": ""},
                                {"name": "nameChanged", "title": "de", "original": "d"},
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "404",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8645129269811969",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "request-id": "MESSAGE:11519203:8645129269811969:5",
                    "x-request-id": "fdee7d21-ea71-4413-a831-7cd360ad1c49",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:11519203:8645129269811969:5",
                    "token": "7a_5fk_ROMP",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "7a_5fk_ROMP",
                            "version": 1,
                            "content": [
                                {"name": "nameChanged", "title": "d", "original": "de"},
                                {"name": "nameChanged", "title": "", "original": "d"},
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "452",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8645129269811969",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "request-id": "MESSAGE:11519203:8645129269811969:7",
                    "x-request-id": "47839a3c-8979-405c-8549-009810cbb389",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:11519203:8645129269811969:7",
                    "token": "7a_5fk_ROMP",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "7a_5fk_ROMP",
                            "version": 2,
                            "content": [
                                {"name": "nameChanged", "title": "", "original": ""},
                                {"name": "nameChanged", "title": "d", "original": ""},
                                {"name": "nameChanged", "title": "de", "original": "d"},
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "412",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8645129269811969",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "request-id": "MESSAGE:11519203:8645129269811969:9",
                    "x-request-id": "b07d52b9-2557-4670-990f-39d414aed9c8",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 9,
                    "requestId": "MESSAGE:11519203:8645129269811969:9",
                    "token": "7a_5fk_ROMP",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "7a_5fk_ROMP",
                            "version": 3,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "dem",
                                    "original": "de",
                                },
                                {
                                    "name": "nameChanged",
                                    "title": "demo",
                                    "original": "dem",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .options("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "content-length": "52",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "a98ec40a-3969-4846-aa08-f5c51effe298",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "7a_5fk_ROMP", "keywords": "demo", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "459",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8645129269811969",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "request-id": "MESSAGE:11519203:8645129269811969:11",
                    "x-request-id": "84ebe693-f751-4218-9a93-14d49555c3c9",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 11,
                    "requestId": "MESSAGE:11519203:8645129269811969:11",
                    "token": "7a_5fk_ROMP",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "7a_5fk_ROMP",
                            "version": 4,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "kGT4a7JjaF",
                                                "text": "",
                                                "modified": 1616740129077,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "505",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8645129269811969",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "request-id": "MESSAGE:11519203:8645129269811969:13",
                    "x-request-id": "a6bcb12a-2084-4280-ae79-5f2b60db30a7",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 13,
                    "requestId": "MESSAGE:11519203:8645129269811969:13",
                    "token": "7a_5fk_ROMP",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "7a_5fk_ROMP",
                            "version": 5,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "kGT4a7JjaF",
                                                "text": "<span>1111</span>",
                                                "modified": 1616740130768,
                                            },
                                            "original": {
                                                "id": "kGT4a7JjaF",
                                                "text": "",
                                                "modified": 1616740129077,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "459",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8645129269811969",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "request-id": "MESSAGE:11519203:8645129269811969:15",
                    "x-request-id": "897dc87a-8b4a-4941-8f1c-1db32c4ec5b7",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 15,
                    "requestId": "MESSAGE:11519203:8645129269811969:15",
                    "token": "7a_5fk_ROMP",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "7a_5fk_ROMP",
                            "version": 6,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "z8Z6V9Bfds",
                                                "text": "",
                                                "modified": 1616740131061,
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "505",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8645129269811969",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "request-id": "MESSAGE:11519203:8645129269811969:17",
                    "x-request-id": "0dbffcf0-bf0d-4ccb-b6f6-b60bd6fd094f",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 17,
                    "requestId": "MESSAGE:11519203:8645129269811969:17",
                    "token": "7a_5fk_ROMP",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "7a_5fk_ROMP",
                            "version": 7,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "z8Z6V9Bfds",
                                                "text": "<span>2222</span>",
                                                "modified": 1616740135216,
                                            },
                                            "original": {
                                                "id": "z8Z6V9Bfds",
                                                "text": "",
                                                "modified": 1616740131061,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "42",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "x-request-id": "45d3f151-dabb-4a40-9c2d-2512a1bc9067",
                    "version": "3.0.0.21221",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "6RqNlAlNnMP", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "226",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8645129269811969",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "199514d6-b241-4830-949e-08ad0b387abf",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTkzMzIwODEsImlhdCI6MTYxNjc0MDA4MX0.DjcnGeqsHUN4f734hFM6YzWYbYinEIf0xGTO3NP02Pmt7tu54BzU0wi-KmZoYPl7xmhX4Sjt9VNVDIuEvQnTZQ",
                    "request-id": "MESSAGE:11519203:8645129269811969:19",
                    "x-request-id": "ebcc4a3e-fbd8-4fd8-8f71-b6767be0f165",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "UNWATCH",
                    "reqId": 19,
                    "requestId": "MESSAGE:11519203:8645129269811969:19",
                    "token": "7a_5fk_ROMP",
                    "data": {},
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubu().test_start()
