# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubu(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/login")
            .get("https://mubu.com/login")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616984547",
                    "_ga": "GA1.2.846317235.1616984547",
                    "_gid": "GA1.2.789545346.1616984547",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "csrf_token": "a48ed18c-9922-418e-8572-1ab79daf2186",
                    "SESSION": "31e63492-17e8-4556-940a-683f897c38cf",
                    "_gat": "1",
                    "reg_prepareId": "1787beed02f-1787beecef3-4187-a249-b50c64637caa",
                    "reg_focusId": "f45e83e8-41c6-4187-a249-1787beed357",
                    "_gat_UA-77727571-3": "1",
                    "SLARDAR_WEB_ID": "90a80b40-38e3-49b8-beb3-6789697f4353",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616986997",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("https://mubu.com/login/password")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616984547",
                    "_ga": "GA1.2.846317235.1616984547",
                    "_gid": "GA1.2.789545346.1616984547",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "csrf_token": "a48ed18c-9922-418e-8572-1ab79daf2186",
                    "SESSION": "31e63492-17e8-4556-940a-683f897c38cf",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "reg_prepareId": "1787bef8c89-1787bef8c84-4e0e-8265-3f7bc7eb089a",
                    "SLARDAR_WEB_ID": "91c007d2-504b-463f-95d3-1954e30538a3",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616987000",
                    "reg_focusId": "95b9830b-3673-4e0e-8265-1787bef9055",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "content-length": "51",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616984547",
                    "_ga": "GA1.2.846317235.1616984547",
                    "_gid": "GA1.2.789545346.1616984547",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "csrf_token": "a48ed18c-9922-418e-8572-1ab79daf2186",
                    "SESSION": "31e63492-17e8-4556-940a-683f897c38cf",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "reg_prepareId": "1787bef8c89-1787bef8c84-4e0e-8265-3f7bc7eb089a",
                    "reg_focusId": "95b9830b-3673-4e0e-8265-1787bef9055",
                    "SLARDAR_WEB_ID": "d2f5c0e3-bef5-4c0e-b9ce-8900f7a37b93",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616987001",
                }
            )
            .with_data(
                {"phone": "17876253458", "password": "q992926186", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
            .get("https://mubu.com/app")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616984547",
                    "_ga": "GA1.2.846317235.1616984547",
                    "_gid": "GA1.2.789545346.1616984547",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "csrf_token": "a48ed18c-9922-418e-8572-1ab79daf2186",
                    "SESSION": "31e63492-17e8-4556-940a-683f897c38cf",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "reg_prepareId": "1787bef8c89-1787bef8c84-4e0e-8265-3f7bc7eb089a",
                    "reg_focusId": "95b9830b-3673-4e0e-8265-1787bef9055",
                    "SLARDAR_WEB_ID": "d2f5c0e3-bef5-4c0e-b9ce-8900f7a37b93",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616987001",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "user_persistence": "e12a1282-0f42-4a31-b9c3-c6ffe6b1b677",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "c9174c5f-6cdf-44b3-8a8d-9ef1a5f86e4a",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "294b2c07-d1a9-48e1-9eab-d3c05c2dc902",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "76f98215-8e7b-47a8-8977-bf72f05050a1",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get")
            .post("https://api2.mubu.com/v3/api/list/get")
            .with_headers(
                **{
                    "content-length": "58",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "151b8290-69bb-4c38-b9f5-762423e09503",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {"folderId": 0, "sort": "time", "keywords": "", "source": "home"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "content-length": "12",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "c4c44e2a-521c-49b4-b949-9e441f4026cd",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "9544256b-b4ae-405b-ad9e-b0db3d42d8db",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "d802bbab-43e4-444b-af52-cffdaec5d792",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "4e5c6be4-2fc3-4ea3-8302-b6422572b8a5",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "294b2c07-d1a9-48e1-9eab-d3c05c2dc902",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_folder")
            .post("https://api2.mubu.com/v3/api/list/create_folder")
            .with_headers(
                **{
                    "content-length": "39",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "d61d5393-380e-4093-8ab8-ccc22237eab6",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"name": "hogwarts_demo1", "folderId": "0"})
            .extract()
            .with_jmespath("body.data.folder.id", "folderId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "42",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "23aa7c2f-b2cd-45d9-88a8-efca0159c3ea",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "$folderId", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "35",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "4b1de05c-27eb-47a3-9b12-fe593d135572",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "$folderId", "type": 0})
            .extract().with_jmespath("body.data.id", "docId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "8a0bf067-38f6-4a04-93e2-97fafe9cbe69",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "content-length": "36",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "c4c7ee19-5106-4a5e-8369-54c986004789",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "$docId", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "28",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "039663d7-1d39-41b5-a162-97c06f8f4888",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"document_id": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "x-request-id": "7a2a6c0c-d53e-4aa6-83d5-1f1de9e2087e",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "content-length": "28",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "68993915-12f2-418b-b8f5-4096f1928821",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/node/count")
            .post("https://api2.mubu.com/v3/api/refer/node/count")
            .with_headers(
                **{
                    "content-length": "28",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "40963432-d90a-4606-a478-268cd79883dc",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"memberId": "8441273827244994", "documentId": "$docId"})
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"memberId": "8441273827244994", "documentId": "$docId"})
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "request-id": "members:8441273827244994:1616987023394",
                    "x-request-id": "4ea4da7a-9d94-448c-b1ab-e0d83ac4508c",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "402",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8441273827244994",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "request-id": "MESSAGE:11519203:8441273827244994:3",
                    "x-request-id": "b407e4d7-a50c-4bb2-8f80-53fbffe4cf6d",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:11519203:8441273827244994:3",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 0,
                            "content": [
                                {"name": "nameChanged", "title": "c", "original": ""},
                                {"name": "nameChanged", "title": "ce", "original": "c"},
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "402",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8441273827244994",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "request-id": "MESSAGE:11519203:8441273827244994:5",
                    "x-request-id": "084c730d-e90b-495c-bd7f-232da57fbc0a",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:11519203:8441273827244994:5",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 1,
                            "content": [
                                {"name": "nameChanged", "title": "c", "original": "ce"},
                                {"name": "nameChanged", "title": "", "original": "c"},
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "356",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8441273827244994",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "request-id": "MESSAGE:11519203:8441273827244994:7",
                    "x-request-id": "67527442-e479-4ee7-b100-1c9862234645",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:11519203:8441273827244994:7",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 2,
                            "content": [
                                {"name": "nameChanged", "title": "测试", "original": ""}
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "content-length": "53",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "2365c382-cf09-44ad-a43b-40a3647a1f10",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "$docId", "keywords": "测试", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "455",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8441273827244994",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "request-id": "MESSAGE:11519203:8441273827244994:9",
                    "x-request-id": "d88453ab-d165-47e4-b47b-2833961b67d7",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 9,
                    "requestId": "MESSAGE:11519203:8441273827244994:9",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 3,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "3IjytDBinY",
                                                "text": "",
                                                "modified": 1616987027757,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "501",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8441273827244994",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "request-id": "MESSAGE:11519203:8441273827244994:11",
                    "x-request-id": "680e5d7f-56aa-4b2d-95ae-5528b5cf2374",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 11,
                    "requestId": "MESSAGE:11519203:8441273827244994:11",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 4,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "3IjytDBinY",
                                                "text": "<span>11</span>",
                                                "modified": 1616987030666,
                                            },
                                            "original": {
                                                "id": "3IjytDBinY",
                                                "text": "",
                                                "modified": 1616987027757,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "670",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8441273827244994",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "request-id": "MESSAGE:11519203:8441273827244994:13",
                    "x-request-id": "ddaf1292-c977-4d16-81c5-f60bfdd0f64e",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 13,
                    "requestId": "MESSAGE:11519203:8441273827244994:13",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 5,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "3IjytDBinY",
                                                "text": "<span>111</span>",
                                                "modified": 1616987030799,
                                            },
                                            "original": {
                                                "id": "3IjytDBinY",
                                                "text": "<span>11</span>",
                                                "modified": 1616987030666,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "vNnYnG2D5b",
                                                "text": "",
                                                "modified": 1616987031118,
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "503",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8441273827244994",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "request-id": "MESSAGE:11519203:8441273827244994:16",
                    "x-request-id": "91c4acbd-6ba9-4716-8d62-5669ec4b9755",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 16,
                    "requestId": "MESSAGE:11519203:8441273827244994:16",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 6,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "vNnYnG2D5b",
                                                "text": "<span>2222</span>",
                                                "modified": 1616987031880,
                                            },
                                            "original": {
                                                "id": "vNnYnG2D5b",
                                                "text": "",
                                                "modified": 1616987031118,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "42",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "x-request-id": "e6163bc4-12a6-4386-bea5-1623c3211ee0",
                    "version": "3.0.0.21267",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "$folderId", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "225",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "8441273827244994",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "c8f45955-c3d6-4125-806e-86b88a48ea00",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE1MTkyMDMiLCJleHAiOjE2MTk1NzkwMDYsImlhdCI6MTYxNjk4NzAwNn0.UkoxYxcNYZIwajtr9_6pZ_4UDg4wl3XucRoa22UiGSECCYQy53v5Rra81JxtrGB3M2vTBEnBP40RTY58fuR7Ag",
                    "request-id": "MESSAGE:11519203:8441273827244994:18",
                    "x-request-id": "4d27356f-b238-43cc-8112-328f89296fd7",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "UNWATCH",
                    "reqId": 18,
                    "requestId": "MESSAGE:11519203:8441273827244994:18",
                    "token": "$docId",
                    "data": {},
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubu().test_start()
